X25519MLKEM768 to MLKEM768X25519
post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem pull request #26
Opened 2024-12-11 00:00 UTC by kriskwiatkowski

This is done to align with the requirement described in section 3.2 of draft-ietf-tls-hybrid-design-11.

2024-12-11 00:27 UTC, bwesterb commented
I don't believe there is working group consensus to make this change.

2024-12-11 00:42 UTC, kriskwiatkowski commented
Ha! I calculated (zulip + mailing list), 5 people prefer to swap, 4 people prefer not to, 2 people undecided/don't care.
The other thing we could is just to mention that the name X25519MLKEM768 is kind of exception and it is not aligned with draft-tls-hybrid. And that's it.

Frankly, I would like to find consensus (whatever it is) and push for adoption of the draft.

2024-12-11 03:15 UTC, csosto-pk commented
> X25519MLKEM768 is kind of exception and it is not aligned with draft-tls-hybrid. 

I think that is painless enough. Did it come up in the list a people objected? I don't remember.

2024-12-11 04:28 UTC, dconnolly commented
> > X25519MLKEM768 is kind of exception and it is not aligned with draft-tls-hybrid.
> 
> I think that is painless enough. Did it come up in the list a people objected? I don't remember.

I did 🫣

2024-12-11 08:40 UTC, kriskwiatkowski commented
How about that, than https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem/pull/27?

2024-12-11 16:24 UTC, dconnolly commented
Since the wire format is the same, the codepoint is the same, it should align with -hybrid-design and have the name match the wire format, as intended

2024-12-11 16:36 UTC, bwesterb commented
If you are a developer and see these two choices:

- P256MLKEM768
- MLKEM768X25519

The user might think: why is the MLKEM769 in a different place? Does it matter?

Of course the order is immaterial. It's less confusing if we just use the names.

- P256MLKEM768
- X25519MLKEM768

Of course this is more confusing to the crypto engineer that need to implement this in TLS libraries. But there are many more developers picking KEMs then there are crypto engineers implementing them. We shouldn't move undue complexity to the enduser.

2024-12-11 16:54 UTC, davidben commented
I do agree it would be a poor outcome if the names were different like that. It is... unfortunate that we ended up making the wire order inconsistent but the wire order impacts fewer people than the names.

2024-12-11 17:29 UTC, dconnolly commented
To be clear, this is a MUST in [-hybrid-design](https://www.ietf.org/archive/id/draft-ietf-tls-hybrid-design-11.html):

<img width="760" alt="image" src="https://github.com/user-attachments/assets/bdc6614c-ea3a-4cc8-965c-05e37703b87c" />

2024-12-11 17:30 UTC, FiloSottile commented
Strong preference for keeping X25519MLKEM768.

We already deployed it under that name and it's forever seared into our backwards-compatibility promise. golang/go#69985

I also find the argument in https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem/pull/26#issuecomment-2536502901 persuasive. There are dozens (maybe less?) of implementers and tens of thousands (maybe more?) system administrators that will be exposed to these names. 

I'd even argue to change the overall rule to `[non-PQ][PQ]` in -hybrid-design.

2024-12-11 17:34 UTC, dconnolly commented
> Strong preference for keeping X25519MLKEM768.
> 
> We already deployed it under that name and it's forever seared into our backwards-compatibility promise. [golang/go#69985](https://github.com/golang/go/issues/69985)
> 
> I also find the argument in [#26 (comment)](https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem/pull/26#issuecomment-2536502901) persuasive. There are dozens (maybe less?) of implementers and tens of thousands (maybe more?) system administrators that will be exposed to these names.
> 
> I'd even argue to change the overall rule to `[non-PQ][PQ]` in -hybrid-design.

You made backwards-compatibility commitments on an unstable document?

2024-12-11 17:35 UTC, dconnolly commented
> Strong preference for keeping X25519MLKEM768.
> 
> We already deployed it under that name and it's forever seared into our backwards-compatibility promise. [golang/go#69985](https://github.com/golang/go/issues/69985)
> 
> I also find the argument in [#26 (comment)](https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem/pull/26#issuecomment-2536502901) persuasive. There are dozens (maybe less?) of implementers and tens of thousands (maybe more?) system administrators that will be exposed to these names.
> 
> I'd even argue to change the overall rule to `[non-PQ][PQ]` in -hybrid-design.

Also -hybrid-design has already gone through last call

2024-12-11 17:42 UTC, FiloSottile commented
I deployed a security-relevant improvement to my users, the same that's deployed by browsers and CDNs, and referred to it by its current name. I stand by that choice.

-hybrid-design is a sign, not a cop, and it would be a deeply sad outcome if we deliberately chose to sign up thousands of people for confusion because we feel we can't amend a last call or add a note saying it doesn't match a document that anyway AFAICT is not necessary to implement X25519MLKEM768.

Looking at this thread, X25519MLKEM768 has rough consensus and running code.

2024-12-11 17:48 UTC, FiloSottile commented
Also, the IANA registry already has an entry for 4588 with name X25519MLKEM768.

https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8

It feels completely legitimate to rely on names in the IANA registry not to change. Can IANA registries be changed in a non-backwards compatible way? What would even be the point of IANA then?

2024-12-11 18:03 UTC, kriskwiatkowski commented
@FiloSottile, _if_ we proceed with this change, then the plan is to update this name in IANA without modifying the code point value.

2024-12-12 17:06 UTC, tomato42 commented
@FiloSottile
> Also, the IANA registry already has an entry for 4588 with name X25519MLKEM768.
> 
> https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8
> 
> It feels completely legitimate to rely on names in the IANA registry not to change. Can IANA registries be changed in a non-backwards compatible way? What would even be the point of IANA then?

the IDs in IANA referenced by drafts can definitely change, they're not immutable

while I agree that changing the name is painful, providing an alias, where both `X25519MLKEM768` and `MLKEM768X25519` will work to enable the same group isn't insurmountable

and just looking at gnutls, openssl and NSS I see different names for this fundamentally the same group already; hell, we've had OpenSSL refer to `secp256r1` as `prime256v1`  as basically the only implementation and the internet still managed to widely deploy it, so it's not like Go _needs_ to change the name to align it with IANA

at the end of the day, the users don't care (or even know) what key exchange they use, as long as the connection works, they're happy

2024-12-12 18:25 UTC, rolandshoemaker commented
Chiming in as a maintainer of the Go crypto libraries. While I understand the intent behind this change, I would like to add that this seems likely to cause more pain and confusion than it is likely to solve. The mismatch between the name and wire format is unfortunate, but that property is likely of important to 1% of the people who will be exposed to the name.

Switching now, after many libraries have already deployed using the current name, and much documentation, and many blog posts have been written using the current name, feels like it'd cause significant confusion.

As a library maintainer, the idea that users don't need to worry about these naming choices strikes me as incorrect. The confusing naming choices of ciphersuites and crypto primitives, and a lack of consistency around them, turns out to be a consistent pain point for users, and for maintainers who have to answer their questions. The NIST P-256/secp256r1/prime256v1 confusion is still something we get questions about, and the RFC 8422 Appendix A "clarifications" have done nothing to prevent this.

In this case we are perhaps lucky that the proposed change is just reversing the order, but I would put a not insignificant amount of money on the fact that if the name changes now, I'll be fielding questions about whether X25519MLKEM768 is the same thing as MLKEM768X25519, or why we don't implement one or the other, for the foreseeable future.

For better or worse, (quite a bit of) deployed software now uses the name X25519MLKEM768, and search engines are going to perpetuate this mistake for eternity, whether or not the name is changed at this late point.

2024-12-13 13:43 UTC, alexzas commented
An implementer here adding hybrid MLKEM to our CryptoComply library. I must admit I initially assumed that the order of key shares is dictated by scheme name (which is correct for most other schemes) and spent several days debugging failed connections to Chrome client. 
I wonder if "NIST intends to allow the 800-56C key derivation methods to apply to shared secrets of the form Z = T || Z’, where T and Z’ are ...in reverse order." should help here? 

My assumption is that PQC migration will affect much wider audience, with some not even familiar with FIPS, but they might open wireshark and see inconsistency on the wire. 
   
I hope we are still in the early days of PQC migration and can make things right.. 

my 2c,
Alex

2024-12-13 14:09 UTC, bwesterb commented
> I must admit I initially assumed that the order of key shares is dictated by scheme name (which is correct for most other schemes) and spent several days debugging failed connections to Chrome client.

Sorry about that :(.

> My assumption is that PQC migration will affect much wider audience, with some not even familiar with FIPS, but they might open wireshark and see inconsistency on the wire.

On the wire these are almost uniform random blobs. Technically I can tell the order with good probability (because coefficients mod 3329 are stored in 12 bits), but I doubt a casual user would see that.

2025-01-03 00:51 UTC, vdukhovni commented
I fail to see how the requirement on the wire order of the components matching the order of algorithms defining the hybrid translates to a requirement on the group **name**.  The group **name** `X25519MLKEM768` can easily refer the ordered algorithm pair `(MLKEM768, X25519)`, which then produce their outputs in the widely implemented order expected of the code point. The group name (bikeshed colour) could be `REDBLUE` for all it matters.

Let's not change the name now unless (rather unexpectedly) the wire order is changing and a new code point is being assigned.

2025-01-03 01:38 UTC, vdukhovni requested changes

2025-01-03 01:38 UTC, vdukhovni commented on draft-kwiatkowski-tls-ecdhe-mlkem.md
> +This draft defines three hybrid key agreements for TLS 1.3: MLKEM768X25519,
This confuses identities with identifiers. The name is just an identifier, and so long as the group by that name is defined to be an ordered combination of `ML-KEM-768` (NIST name) and `X25519`, there is no conflict with the hybrid design draft, that draft isn't about how things are named, it is about how they're defined.

So this change feels gratuitous.

2025-01-03 01:38 UTC, vdukhovni commented on draft-kwiatkowski-tls-ecdhe-mlkem.md
> +For this reason we put the ML-KEM shared secret first in MLKEM768X25519,
Whatever the reason, the definition should first state the order of the two component algorithms (state the definition of the group), and only then perhaps give a rationale, or note that in that particular order the result may be better aligned with FIPS (which may or may not be true).

2025-01-03 01:38 UTC, vdukhovni commented on draft-kwiatkowski-tls-ecdhe-mlkem.md
>  and the client's X25519 ephemeral share.
```suggestion
and the client's X25519 ephemeral share, in that order.
```
This finally is the definition of the group, though one could also state that the hybrid algorithm is an ordered combination of `ML-KEM-768` and `X25519` and the wire order is then, in accordance with hybrid-design, ML-KEM first, X25519 second.

2025-01-03 01:38 UTC, vdukhovni commented on draft-kwiatkowski-tls-ecdhe-mlkem.md
> + : Combining ML-KEM-768 with X25519 ECDH
This part is justified, since it is reaffirming the order of the components that the group represents as identified by the group name.

2025-01-03 01:38 UTC, vdukhovni commented on draft-kwiatkowski-tls-ecdhe-mlkem.md
> +  * Change the name of X25519MLKEM768 to MLKEM768X25519. This is done to align with the requirement described in section 3.2 of draft-ietf-tls-hybrid-design-11.
Let's not.

2025-01-15 22:07 UTC, kriskwiatkowski commented
I'll close this PR, it seems most participants to this discussion wish not to do it (including myself now).

2025-01-15 22:07 UTC, closed without merging